CREATE TABLE `dates` (
  `id` int(11) NOT NULL,
  `calendar_date` date NOT NULL,
  `calendar_day` int(11) NOT NULL,
  `calendar_month` int(11) NOT NULL,
  `calendar_year` int(11) NOT NULL,
  `calendar_mon_d_y` char(13) COLLATE utf8_unicode_ci NOT NULL,
  `calendar_m_d_y` char(10) COLLATE utf8_unicode_ci NOT NULL,
  `reporting_y_q_w` char(8) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0000Q0W0',
  `reporting_y_w` char(6) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0000W0',
  `reporting_y_w_d` int(11) NOT NULL,
  `day_of_week_number` int(11) NOT NULL,
  `day_of_week_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `day_of_week_short_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `day_of_week_abv_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `week_number` int(11) NOT NULL,
  `week_short_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `month_number` int(11) NOT NULL,
  `month_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `month_short_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `day_of_month_number` int(11) NOT NULL,
  `quarter_number` int(11) NOT NULL,
  `quarter_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `year_number` int(11) NOT NULL,
  `year_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `day_of_year_number` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_dates_calendar_date` (`calendar_date`),
  KEY `idx_dates_calendar_year` (`calendar_year`),
  KEY `idx_dates_quarter_number` (`quarter_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;